server:
  port: 9090

spring:
  datasource:
    drive-clas-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/CaseDB
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true